- name: allow ssh
  ufw: rule=allow port=22 proto=tcp
  sudo: yes

- name: allow http
  ufw: rule=allow port=80 proto=tcp
  sudo: yes

- name: allow https
  ufw: rule=allow port=443 proto=tcp
  sudo: yes

- name: enable
  ufw: state=enabled
  sudo: yes